name: Build & Publish NuGet Package

on:
  push:
    branches:
      - "main"
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    working-directory: src
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack NuGet Packages
      run: dotnet pack --output nupkgs --no-restore --no-build
    - name: Upload NuGet Package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json